### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by LindaLawton** [Serviceplatformen/demoservice-client-net#11]
This sample is for .NETFramework 4.5.2 which is going to be EOL in April 2022.   

Any chance for an upgrade on this to .net 6?

There is what appears to be full documentation for this [here](https://digitaliseringskataloget.dk/files/integration-files/131120201133/Kom%20godt%20i%20gang%20-%20webservice.pdf)

**Comment by Serviceplatformen** [comment]
Hi

If you still have the isssue please contact helpdesk@serviceplatformen.dk.
We are closing the issue feature.

We have just uploaded a new version using .Net v4.7.2

Regards
ServicePlatformen
