### ISSUE TITLE
09_kombit_sp_t_demo_serv_funktionscertifikat_ certificate expired 10 Aug 2019

### ISSUE THREAD

**Issue by wachulski** [Serviceplatformen/demoservice-client-net#4]
This is what I received after calling the service:

> Calling DemoService with token...
System.ServiceModel.FaultException: Client credential with certificate '3F2272A18337F41A6086C7EF02C086112CCBEF2F' is invalid - Certificate whose thumbprint is 3F2272A18337F41A6086C7EF02C086112CCBEF2F has expired. NotAfter is 08/10/2019 12:0
9:57
   at System.ServiceModel.Security.WSTrustChannel.ReadResponse(Message response)

Another question: Is DemoTokenClient supposed to work correctly with configuration setup already provided - I mean for demonstration purpose only. I know for the real (production) use I need to substitute values, but still - given what in the repo - should I be able to receive valid responses from the server? Why am I asking - since I found DemoClient works like a charm, but I had troubles running DemoTokenClient out of the box.

**Comment by jespertp-systematic** [comment]
This was fixed in commit 274ebe93cb399244f7e99f96abc6b87c21576649
