### ISSUE TITLE
// See document TEN0002 for details. - where can I find it?

### ISSUE THREAD

**Issue by wachulski** [Serviceplatformen/demoservice-client-net#5]
I see remarks `// See document TEN0002 for details.` twice but have no clue where to find them in. I crawled:
 - https://share-komm.kombit.dk/P133/Ibrugtagning%20og%20test/Delte%20dokumenter/Forms/Vejledninger%20%20Serviceplatformen.aspx and 
- https://share-komm.kombit.dk/P133/_layouts/15/start.aspx#/Integrationsbeskrivelser/Forms/AllItems.aspx

but apparently it's not there.

**Comment by jespertp-systematic** [comment]
Yes, that is not very clear.
For information the TEN0002 is the internal document ID.
It has now been replaced with the name of the document: "Programmers Guide - Serviceplatformen".
The document can be found at Kombits site here:
https://share-komm.kombit.dk/P133/Ibrugtagning%20og%20test/Delte%20dokumenter/Forms/Vejledninger%20%20Serviceplatformen.aspx
